version: "3.7"

services:
  so_client:
    container_name: so_client
    image: ghcr.io/vmatyagin/so_client:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
