version: "3"
services:
    client:
      stdin_open: true
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      volumes:
        - "/home/node/app/node_modules"
        - "./:/home/node/app"
      environment:
        - CHOKIDAR_USEPOLLING=true